### PR TITLE
Dependencies management with gradle-kotlin-dsl-libs

### PR DESCRIPTION
**Pull request by jmfayard**
Hello,

I wrote a Gradle plugin to make dependencies management better.

I explain here the Why?, What? and How?

https://github.com/jmfayard/gradle-kotlin-dsl-libs

I will update just one Gradle module so that you can have a look and tell me what you think / wether you encounter any issues

### CODE REVIEW

**Comment by jmfayard** [comment]
I don't think this error has something to do with me

```
> Task :api:circleci:kaptKotlin
FAILURE: Build failed with an exception.
Could not resolve all files for configuration ':bugsnag-tree:lintClassPath'.
> Could not download trove4j.jar (org.jetbrains.trove4j:trove4j:20160824): Skipped due to earlier error
```

**Comment by JakeWharton** [comment]
I have no interest in supporting the use of Gradle's Kotlin DSL in this project. The dependencies are already de-duplicated and the Ben Manes plugin checks for updates. It's not a pain point, and I don't want to introduce Gradle Kotlin DSL which is a giant pain point.

**Comment by jmfayard** [comment]
ok!

**Comment by bentarve** [comment]
> I have no interest in supporting the use of Gradle's Kotlin DSL in this project. The dependencies are already de-duplicated and the Ben Manes plugin checks for updates. It's not a pain point, and I don't want to introduce Gradle Kotlin DSL which is a giant pain point.

Can you elaborate more on this please? I was just wondering for new fresh projects

**Comment by jmfayard** [comment]
@bentarve
well the answer was fair game because it came before Kotlin was officially supported in Gradle 5.0

should you configure your Gradle build with Kotlin today?

it depends if you are doing Android or not.

currently Kotlin is a greay choice if you do spring development in IntelliJ IDEA

if you are doing Android development in Android studio, honestly I would procradtinaste on adopting Kotlin Gradle because there are obvious bugs that are not fixed in Android studio and no documentation for Kotlin snippets in the Android Gradle plugin

**Comment by bentarve** [comment]
@jmfayard 
Thank you for your clarification

**Pull request closed without merging**
