### PR TITLE
Updated (adaptive) icon.

### PR DESCRIPTION
**Pull request by nickbutcher**
Fixes # 46

adaptive_icon

### CODE REVIEW

**Comment by nickbutcher** [comment]
Didn't create raster or round icons because `minSdk = 26`

**Comment by nickbutcher** [comment]
cc/ @romannurik

**Comment by JakeWharton** [comment]
I'm attempting to lower the minSdk so we'll need raster eventually. I can make an attempt to export those, unless it's _really_ easy for you to do now.

**Comment by nickbutcher** [comment]
I can do it.

**Comment by JakeWharton** [comment]
Hah the lint check I suggested is tripping it up. Merging and will fix after.

**Comment by JakeWharton** [comment]
Thanks!

**Comment by nickbutcher** [comment]
No problemo. The fix is [here](https://github.com/nickbutcher/SdkSearch/commit/b3ebd45) but you'd already merged 🤠.

**Comment by JakeWharton** [comment]
I'm going to try lowering min to 24. I believe there's a Sqlite problem in
older versions that Chris found but I'm not sure on which version is starts.

**Comment by JakeWharton** [comment]
Seems to work on 24!

**Comment by romannurik** [comment]
Gorgeous!

**Comment by vilius-kraujutis-ht** [comment]
Oh, that's cool! And it's already in Google Play. Nice!

Also I had a question, is this adaptiveness feature visible only when icon is being added to home screen? When it's already in home screen, I can't see it animating.

**Comment by nickbutcher** [comment]
@vilius-kraujutis-ht That's up to individual launchers! Yes the Pixel Launcher (at this time) only applied motion effects when you're dragging the icon but other launchers are free to innovate here. It's just two stacked layers!

**Pull request merged**
