### PR TITLE
Tweaks to Android list item presentation

### LINKED ISSUE #12: Redesign result line items
No one likes the abbreviated package names, and even after staring at them for weeks it's hard for me to parse some of them...

### PR DESCRIPTION
**Pull request by chrisbanes**
Package and class name are now split over two TextViews. Both are now using autosizing to combat against long names (mainly for inner classes). Also added item dividers which improve legibility.

screenshot_1516112270

Closes #12

### CODE REVIEW

**Comment by JakeWharton** [comment]
Any idea why the two OnMenuItemClickListener rows have different font size? They should measure exactly the same.

**Comment by chrisbanes** [comment]
Hmmm, might be due to auto sizing textview not resetting itself? I'll see if I can fix in a new PR

**Comment by chrisbanes** [comment]
Weird, I can't repro now 😕

**Comment by JakeWharton** [comment]
I basically only use "Toolbar" in manual testing so I'll keep an eye out.

**Pull request merged**
